<?php  //[STAMP] 3422fbe61aa379a50160a982314a38e3
// phpcs:ignoreFile
namespace XiphiasTest\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
